### ISSUE TITLE
Add missing batchnorm test cases 

### ISSUE THREAD

**Issue by muralinr** [ROCm/MIOpen#1020]
Add missing batchnorm test cases and adjust error thresholds if necessary..

**Comment by atamazov** [comment]
Originated from https://github.com/ROCmSoftwarePlatform/MIOpen/pull/974#issuecomment-860793839

**Comment by ppanchad-amd** [comment]
@muralinr, Is this implemented? If so, can we close this ticket? Thanks!

**Comment by muralinr** [comment]
Artem updated test cases. We are phasing out old MIOPEN batchnorm code.  This ticket was related to old code.  Can you please close this ticket?
