### ISSUE TITLE
Error on CI builds with status code 8

### ISSUE THREAD

**Issue by kahmed10** [ROCm/MIOpen#1061]
Using develop branch commit 1ebf0216930f672994c341d3c29c9d670cfd3cf8, I am seeing MIOpen fail on a specific unit test. I am attaching the log file for more info. This behavior is only showing up on Jenkins (vega 20 GPU), and I am unable to reproduce locally.

[fusion_ci_fail.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6889198/fusion_ci_fail.txt)

**Comment by junliume** [comment]
It looks similar to https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/issues/570, CI issue which is not able to reproduce locally.
@JehandadKhan  could you take a look?

**Comment by kahmed10** [comment]
@junliume yes this was the same issue reinvestigated with a newer MIOpen build. The difference here is that we are no longer seeing the `MIOpen(HIP): Error [BaseGetSolution] result.out_pix_tile1 == 0 || result.out_pix_tile0 == 0`, but still it is not passing.

**Comment by atamazov** [comment]
@kahmed10 What is the last good (passing) known commit of MIOpen? Is it possible to identify the offending MIOpen commit?

The failing app is `test_conv_bn_add` from MIGraphX tests. How do we reproduce the issue?

**Comment by kahmed10** [comment]
@atamazov this was reported first while we moved to MIOpen 2.3, but I'm not sure the exact commit which breaks the CI.

As for reproducing, I've shared the log of what is being called into MIOpen, but it's basically a conv_bias_relu fusion.
Conv input: (1, 128, 56, 56)
Weight input: (256, 128, 1, 1)
padding: 0, 0
strides: 1, 1
dilation: 1, 1
Bias input: (1, 256, 56, 56)

**Comment by atamazov** [comment]
@kahmed10 Couple of questions that might be useful for the assignee:
- Vega20, HIP backend, Release build of MIOpen?
- What is the version of HIP compiler/runtime - 4.2 release?

Please also set urgency label on this ticket, thanks.

**Comment by kahmed10** [comment]
> @kahmed10 Couple of questions that might be useful for the assignee:
> 
> * Vega20, HIP backend, Release build of MIOpen?
> * What is the version of HIP compiler/runtime - 4.2 release?
> 
> Please also set urgency label on this ticket, thanks.

I provided the MIOpen branch I used for testing above (HIP backend): 1ebf021
4.2 versions of HIP compiler/runtime.

**Comment by kahmed10** [comment]
If it's easy to explain the errors in the log, please feel free to do so as well. Priority is set to medium, but I would first like to see if this error can be reproduced.

**Comment by kahmed10** [comment]
@atamazov @JehandadKhan I found a similar issue in MIOpen when testing fusion with the following configs:
Conv input: (1, 64, 56, 56)
Weight input: (64, 64, 1, 1)
padding: 0, 0
strides: 1, 1
dilation: 1, 1
Bias input: (1, 64, 56, 56)

Using ROCm 4.2 on CI. Any updates on what could be causing the issue?

**Comment by junliume** [comment]
@kahmed10  revive an old thread: has the urgency level of this ticket been changed?
Any change that you can update to ROCm4.3.1 as CI environment, the same as MIOpen does?

To get back to Artem's inquiries, it's better if we can identify the commit (or range or commits) which might have caused the issue. Would it be easy for you to build MIOpen within your existing docker image and try bi-sectioning to start with?

CC: @causten @JehandadKhan @atamazov

**Comment by kahmed10** [comment]
@junliume urgency hasn't changed, but I have not heard anything with regards to what the error in the log means, or how it can even be triggered.

I will try to rebuild with ROCm 4.3.1. If it still fails, then I will try to identify the last passing MIOpen version.

**Comment by kahmed10** [comment]
@junliume @atamazov the test still fails on ROCm 4.3.1.

The problem with trying to find a version pre-2.3 is the compiler change from hcc to hip-clang. Most likely MIGraphX will not work with hcc anymore, and MIOpen pre-2.3 looks to not be able to compile using hip-clang without this workaround: https://github.com/ROCmSoftwarePlatform/MIOpen/commit/15e7dfe25634ffd85887f974c8458a2ce1ceef11

But that is tagged as MIOpen 2.4. Any suggestions on how to move forward?

**Comment by atamazov** [comment]
@kahmed10 Are you using some old version of MIOpen with ROCm 4.3.1?

**Comment by atamazov** [comment]
@kahmed10  Probably I see. You would like to bisect and find the failing commit. This would be very hard to do. I would prefer debugging.

**Comment by kahmed10** [comment]
@atamazov No. I tested using develop branch with commit 1ebf0216930f672994c341d3c29c9d670cfd3cf8 on ROCm 4.3.1. I can try a newer commit, but I don't think that will solve the problem.

**Comment by atamazov** [comment]
@kahmed10 Please try the most recent develop. 1ebf021 is too outdated.

**Comment by kahmed10** [comment]
@atamazov ok. You can keep track of the errors as they arrive on Jenkins:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FAMDMIGraphX/activity?branch=miopen_test

**Comment by atamazov** [comment]
> @atamazov @JehandadKhan I found a similar issue in MIOpen when testing fusion with the following configs:
> Conv input: (1, 64, 56, 56)
> Weight input: (64, 64, 1, 1)
> padding: 0, 0
> strides: 1, 1
> dilation: 1, 1
> Bias input: (1, 64, 56, 56)

@JehandadKhan Can we reproduce the issue using the above info?

**Comment by ppanchad-amd** [comment]
@kahmed10, Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if this issue still exists? If resolved, please close the ticket. Thanks.
