### ISSUE TITLE
Simple GEMM Example with Xdlops

### ISSUE THREAD

**Issue by raikonenfnu** [ROCm/MIOpen#1091]
Hey guys, I am trying to set up a toy example of gemm using xdlops with the miopen, I was wondering if there are any simple examples on doing such, the closest things I have seen that give extra info is [gemm.hpp](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/kernels/composable_kernel/include/tensor_operation/xdlops_gemm.hpp) and [amd_xdlops.hpp] refered by Jack Chung and (https://github.com/ROCmSoftwarePlatform/MIOpen/blob/c701af3ba83f8fb99d7efab30ee0b22de57f2f42/src/kernels/composable_kernel/include/utility/amd_xdlops.hpp).

Jack also mentioned to tag @zjing14 who is apparently the expert in this field 😄 . Thanks in advance!

**Comment by raikonenfnu** [comment]
My final goal is to bring up a simple MLIR based gemm that runs on xdlops in [ROCm MLIR](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir), I have seen the [examples]( [miopen_xdlops_gemm_v2_one_result_f16](https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/d0bc2c956231415039e51da3a0ac6f3d398f8b4a/mlir/test/Dialect/MIOpen/ops_blockwise_f16.mlir#L38)) but still don't quite understand how the matrixA and matrixB is size of memref<12288xf16, 3>, even though m,n=256, and k = 16

**Comment by whchung** [comment]
+ @junliume for awareness.

**Comment by junliume** [comment]
@raikonenfnu Thanks for getting in touch. Would you be interested in a brief intro meeting so that we can understand your requests more effectively? My contact email is listed under profile, and we can start from there to try to set something up next week. And thanks to @whchung !
CC: @zjing14 we can continue discussion thread here too, in case the request looks clear to you.

**Comment by raikonenfnu** [comment]
> @raikonenfnu Thanks for getting in touch. Would you be interested in a brief intro meeting so that we can understand your requests more effectively? My contact email is listed under profile, and we can start from there to try to set something up next week. And thanks to @whchung !
> CC: @zjing14 we can continue discussion thread here too, in case the request looks clear to you.

Sounds good! will shoot you an email and set up a meeting with my boss as well 😄

**Comment by raikonenfnu** [comment]
sent an email, my email is stanley@nod-labs.com

**Comment by junliume** [comment]
@raikonenfnu has the issue been resolved for you?
