### ISSUE TITLE
"Unable to read system database file" warning

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCm/MIOpen#1218]
If the user doesn't have the MIOpen kernels package installed, they see a message such as below:
`MIOpen(HIP): Warning [SQLiteBase] Unable to read system database file:gfx906_60.kdb Performance may degrade`

This message could be improved to point the uninitiated user to instructions on installing the miopen kernels package:  https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package

The following documentation should also be updated with the above link:
https://rocmsoftwareplatform.github.io/MIOpen/doc/html/cache.html#installing-pre-compiled-kernels

**Comment by ppanchad-amd** [comment]
@jithunnair-amd Please confirm if this has been fixed. If so, please close ticket. Thanks!
