### ISSUE TITLE
[TESTS] Add/fix tests for batched transpose

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#1266]
Let's add tests for batched transpose, so issues like #1265 won't show up anymore.

**Comment by carlushuang** [comment]
@atamazov , the batched transpose I do added a test, but it is for nchw<->nhwc transform [test/gpu_nchw_nhwc_transpose.cpp](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/test/gpu_nchw_nhwc_transpose.cpp)

nchw<->nhwc transform will use batched transpose internally, do you mean add another dedicated batched_tranpose test?

**Comment by atamazov** [comment]
@carlushuang Any test that is able to catch the error from #1265 looks Ok to me.

**Comment by carlushuang** [comment]
@atamazov OK, then I think we already have one :)  test/gpu_nchw_nhwc_transpose.cpp

**Comment by atamazov** [comment]
@carlushuang Good! But the remaining question is: why it didn't caught the #1265 problem when COMGR was enabled by default?

**Comment by carlushuang** [comment]
@atamazov that test need to compile the hip code: `batched_transpose.cpp`, and, actually I don't know the reason... that test will run by default on any arch, and actually https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1247 also need to utilize this kernel ( compile this kernel), so I think we need this kernel compiled everywhere...

**Comment by atamazov** [comment]
@carlushuang If `test_gpu_nchw_nhwc_transpose` is used, but compilation of `batched_transpose.cpp` didn't fail (-DMIOPEN_USE_COMGR=On, before #1265), then `batched_transpose.cpp` is not really used by the test. This must be fixed ASAP, I believe.

**Comment by carlushuang** [comment]
@atamazov I did test locally, build MIOpen with `-DMIOPEN_USE_COMGR=On` and then try `make check`, and with out PR:#1265, it will fail in `test_gpu_reference_kernel`
![image](https://user-images.githubusercontent.com/8322173/141241897-04ec48e5-fee0-4c7c-a274-fb0a4488660e.png)
So I think this test do can detect the comgr problem. But I don't know why previously CI didn't face with this problem...

**Comment by atamazov** [comment]
@carlushuang This is different problem. You need to add LLVM_PATH for COMGR due to some SWDEV, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1253/files#r747517006

**Comment by ppanchad-amd** [comment]
@carlushuang Is this fixed with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
