### ISSUE TITLE
questions encountered when migrating cudnn to miopen.

### ISSUE THREAD

**Issue by MOLOjl** [ROCm/MIOpen#1303]
I notice cudnn has a function `cudnnConvolutionBiasActivationForward()`, it fuses bias and activation into the convolution operator, does miopen support the same function?

**Comment by carlushuang** [comment]
Yes we have fusion support. Currently we have slightly different API structure with cudnn, please see [Getting_Started_FusionAPI](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/Getting_Started_FusionAPI.md) for how to use fusion related API

**Comment by MOLOjl** [comment]
that's cool!
by the way, I'm expanding a library (named onednn), trying to add a HIP branch to it, so I need to transpose some cudnn API to miopen, but I barely know about miopen, so I prepare to ask my questions all in this trace if you don't mind.
if it's not proper, please let me know.

**Comment by MOLOjl** [comment]
I encounter another question today
cudnn has a function defined like this
```c++
cudnnStatus_t cudnnFindConvolutionForwardAlgorithm(
    cudnnHandle_t                      handle,
    const cudnnTensorDescriptor_t      xDesc,
    const cudnnFilterDescriptor_t      wDesc,
    const cudnnConvolutionDescriptor_t convDesc,
    const cudnnTensorDescriptor_t      yDesc,
    const int                          requestedAlgoCount,
    int                               *returnedAlgoCount,
    cudnnConvolutionFwdAlgoPerf_t     *perfResults)
```
the corresponding function in miopen seems to have more parameters, 
```c++
miopenStatus_t miopenFindConvolutionForwardAlgorithm(
    miopenHandle_t handle, 
    const miopenTensorDescriptor_t xDesc, 
    const void *x, 
    const miopenTensorDescriptor_t wDesc, 
    const void *w, 
    const miopenConvolutionDescriptor_t convDesc, 
    const miopenTensorDescriptor_t yDesc, 
    void *y, 
    const int requestAlgoCount, 
    int *returnedAlgoCount, 
    miopenConvAlgoPerf_t *perfResults, 
    void *workSpace, 
    size_t workSpaceSize, 
    bool exhaustiveSearch)
```
the description of miopen's function is:
>Search and run the forward convolutional algorithms and return a list of kernel times.

in the meantime, I noticed cudnn's description says
>This function attempts all algorithms available for cudnnConvolutionForward(). ...
>Note: ..., Memory is allocated via cudaMalloc(). ...

does this mean cudnn allocate some test tensors to do the forward convolution and evaluate available algorithms' performance instead of using user-provided tensors (which is miopen's way)?

**Comment by carlushuang** [comment]
> does this mean cudnn allocate some test tensors to do the forward convolution and evaluate available algorithms' performance instead of using user-provided tensors (which is miopen's way)?

@MOLOjl in MIOpen the *findConvolution* API will actually run convolution kernel on GPU and return a fastest, and there are different behaviors for this API, you can refer to [find_and_immediate](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/find_and_immediate.md) for detail.
The behavior of cudnn I think it is hard for us to answer this question.

**Comment by MOLOjl** [comment]
@carlushuang thanks a lot, it looks like the right corresponding API is miopenConvolutionForwardGetSolution(), this is very helpful.
