### ISSUE TITLE
Pure GeMM Mode Support

### ISSUE THREAD

**Issue by iq136boy** [ROCm/MIOpen#1307]
Current MIOpenGeMM takes convolution descriptions (configs) as input to solve GeMM problems (Hip-backend). We need to add GeMM solvers for GeMM problems.
**MIOpen:**
Pure GeMM solvers
APIs that call pure GeMM Solvers (How to add GeMM solvers inside MIOpen?)
**Fin:**
APIs that take pure GeMM solvers (descriptions) to solve GeMM problems
**Tuna:**
Pure GeMM configs in data bases 
Python scripts that provide GeMM support

**Comment by ppanchad-amd** [comment]
@iq136boy Is this fixed with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
