### ISSUE TITLE
Layout Parameters - Error Handling

### ISSUE THREAD

**Issue by technicalgrp89** [ROCm/MIOpen#1311]
convfp16 -n 128 -c 512 -H 28 -W 28 -k 128 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --in_layout nhwc --out_layout nhwc --fil_layout nhwc
MIOpenDriver convfp16 -n 128 -c 512 -H 28 -W 28 -k 128 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --in_layout nhwc --out_layout nhwc --fil_layout nhwc

Results in following Error Message
```
terminate called after throwing an instance of 'miopen::Exception'
  what():  /data/MIOpen/src/include/miopen/tensor_layout.hpp:66: mismatched layout string, unexpect char: N
Aborted (core dumped)
```
Error message needs to be corrected with proper description.

**Comment by atamazov** [comment]
[off-topic] @technicalgrp89 The formatting is a bit weird. Please pay some attention to markdown formatting rules, especially to:
- https://github.github.com/gfm/#example-50
- https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

Formatting fixed.

**Comment by atamazov** [comment]
@technicalgrp89 Please confirm that everything is clear in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1311#issuecomment-1027037206 or ask questions. I'll be happy to help.

**Comment by ppanchad-amd** [comment]
@technicalgrp89 Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
Hi @atamazov. Please advise if we can close this ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@technicalgrp89 Closing ticket due to lack of activity. Please feel free to re-open if you still have the issue with the latest ROCm. Thanks!
