### ISSUE TITLE
[Navi21] BN lefovers from #1386 (ref: SWDEV-292187)

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#1405]
Leftovers from #1386:
- [x] 🙅 DECLINED ~(1) :red_circle: Identify the root reason of BN issue.
  - Is it `lds_reduce2()`? See [here](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1387#issuecomment-1022145303).
- [x] (2) :red_circle: Regression test #1643
- [x] (3) #1408 :yellow_circle: Fix for the "failed" BN driver message 
- [x] 🙅 DECLINED (4) :question: More from `bn_bwd_spatial_num_fix_1` ?
- [x] 🙅 DECLINED (5) :question: Is it possible to implement DPP based reduction for Navi21 and avoid LDS usage?

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1386#issuecomment-1021380312_

**Comment by muralinr** [comment]
Hi Artem,
Current OCL batchnorm code will be phased out soon.  We are not spending time on further development.  We will support blocking batchnorm issues only.

**Comment by atamazov** [comment]
@muralinr 
> Current OCL batchnorm code will be phased out soon. We are not spending time on further development. We will support blocking batchnorm issues only.

If so, then items (1), (4) and (5) are not needed. But we still need (2) and (3).

@junliume Please confirm, thanks!

**Comment by atamazov** [comment]
@muralinr @junliume 
> > Current OCL batchnorm code will be phased out soon. We are not spending time on further development...
> 
> If so, then items (1), (4) and (5) are not needed...

Correction: "not needed" is incorrect. This depends on the ETA of the new BN code. **_What is your current estimation?_**

Until (1) is resolved, we are still in a high risk zone. The longer we are there the higher is probability of problems.

**Comment by muralinr** [comment]
> @muralinr @junliume
> 
> > > Current OCL batchnorm code will be phased out soon. We are not spending time on further development...
> > 
> > 
> > If so, then items (1), (4) and (5) are not needed...
> 
> Correction: "not needed" is incorrect. This depends on the ETA of the new BN code. **_What is your current estimation?_**
> 
> Until (1) is resolved, we are still in a high risk zone. The longer we are there the higher is probability of problems.

@junliume will provide the ETA of the new BN code.

**Comment by junliume** [comment]
> @junliume Let's assume that we do not need to fix items (1), (4) and (5). Regression tests (2) will be added when we have support for MIOpenDriver in tests ready to use (I am working on this).
> 
> The question is: do we still have plans to phase out old OCL kernels and use something better?

Yes, we plan to replace the BN OCL kernels after CK integration, that's why I am trying to disable a few legacy BN and OCL related tests to keep CI stable at the moment.
CC: @asroy @JehandadKhan @zjing14

**Comment by ppanchad-amd** [comment]
@atamazov SWDEV-292187 is fixed and closed.  Can we close this ticket? Thanks!
