### ISSUE TITLE
Remove temp files once MIOpen finishes using them

### ISSUE THREAD

**Issue by JehandadKhan** [ROCm/MIOpen#156]
During compilation MIOpen writes various files to the `/tmp` directory which should be removed once they are not required.

**Comment by atamazov** [comment]
Here we can see how removal of tempfiles was thrown away, https://github.com/AMDComputeLibraries/MLOpen/pull/829 @DrizztDoUrden @pfultz2 @daniellowell

**Comment by JehandadKhan** [comment]
@atamazov Thanks for digging that up. I will create a PR to address this.

**Comment by atamazov** [comment]
@JehandadKhan Nada problemas ;) However the things became more complicated since then. Now we are using sub-directories in temp (that was done for HIP builds which writes includes to disk, I guess, but all build "types" affected). So now we have to remove empty sub-dir in temp. Sad.

**Comment by JehandadKhan** [comment]
It does indeed, the temp directory class actually cleans up after itself (in the destructor) which means either something is bad or all the temp files being left behind are a result of segfaults. I am still investigating before I commit to a solution

**Comment by atamazov** [comment]
@JehandadKhan 
> either something is bad or all the temp files being left behind are a result of segfaults

Something is bad;)

**Comment by aserio** [comment]
@JehandadKhan and @atamazov, Have you been able to return to this issue?

**Comment by atamazov** [comment]
I am not looking at this.

**Comment by JehandadKhan** [comment]
@aserio  I am but I was able to reproduce the issue to the same extent as reported earlier by the MIGraphX team. MeV has not been able to reproduce the issue either, therefore this dropped in priority.

**Comment by aserio** [comment]
@JehandadKhan Thanks!

**Comment by ppanchad-amd** [comment]
Apologies for the lack of response. Please try latest ROCm 6.0.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.

**Comment by atamazov** [comment]
@ppanchad-amd I do not see this issue anymore and recommend closing this ticket.
