### ISSUE TITLE
Disable usage of entities from miopenDataType_t

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#1583]
Disable use entities from miopenDataType_t because this may lead to elusive errors. For more info, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1578#discussion_r889038610.

Proposal:
- Create new header, `miopen_api_wrappers.hpp`. In the header
  - Wrap items from `miopenDataType_t` into enum class
  - Disable usage of items like `miopenHalf` using macros
  - Include `miopen_api_wrappers.h` and use `DataType::Half` instead of `miopenHalf` everywhere and so on.

Like this:
```C++
#include <miopen.h>
namespace miopen {
enum class DataType
{
    Half = miopenHalf;
...
};
} // namespace miopen
#define miopenHalf ERROR_DO_NOT_USE
...
```

@aska-0096 @junliume Suggested labels: urgency_normal, enhancement, quality. Please feel free to assign this to me.

**Comment by atamazov** [comment]
@jerryyin FYI

**Comment by jerryyin** [comment]
@atamazov Thank you! The example is illuminating and it didn't occur to me that we can address it this way. This will nicely convert a runtime problem into compile time errors.

**Comment by pfultz2** [comment]
Alternatively, you could just constrain the constructor to not take enums as inputs:

```cpp
template<class T, MIOPEN_REQUIRES(std::is_convertible<T, std::size_t>{} and not std::is_enum<T>{})>
tensor(T n) : desc(miopen_type<T>{}, {n}), data(n) {}
```

**Comment by pfultz2** [comment]
Even better would be to add a clang-tidy or cppcheck check to warn on implicit conversions of an enum to a integer, which can catch this for any new enum types in the future(like `miopenProblemDirection_t`, or `miopenTensorArgumentId_t`)

**Comment by atamazov** [comment]
@pfultz2 Yep, it is worth trying this approach to see how many explicit conversions are required.

**Comment by atamazov** [comment]
@pfultz2 The potential problem is that warnings on implicit conversions will appear with all enums, and there may be too many of them.

**Comment by atamazov** [comment]
@pfultz2 
> Even better would be to add a clang-tidy or cppcheck check to warn on implicit conversions of an enum to a integer...

Thanks for feedback. I am unable to find anything suitable among clang-tidy checks. Going to try with https://clang.llvm.org/extra/clang-tidy/checks/bugprone/suspicious-enum-usage.html, but, according to the doc, it shouldn't warn implicit enum->int conversions. In cppcheck I do not see any enum-specific checks at all. I am experimenting with clang-tidy right now.

Possibly proceeding with #1608 is the only way to resolve the issue for now. I would appreciate other ideas.

**Comment by pfultz2** [comment]
> I am unable to find exactly the right check in clang-tidy.

Yea there isnt one. We need to add the check. Using a matcher like this will find when enums are passed to functions with integral parameters(you can test this with `clang-query`):

```cpp
implicitCastExpr(hasCastKind("CK_IntegralCast"),
                 hasSourceExpression(expr(hasType(enumType()))),
                 hasParent(callExpr()))
```

We just need to wrap this in a tidy check(with some tests) and submit it to llvm. 

> In cppcheck I do not see any enum-specific checks at all.

Newer cppcheck does have addons to write checks that dont have to be upstreamed:

https://github.com/danmar/cppcheck/blob/main/man/writing-addons.md

But cppcheck doesn't have as complete AST as clang so its not as simple to find such implicit conversions(especially in function calls).

> Possibly proceeding with https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1608 is the only way to resolve the issue for now. I would appreciate other ideas.

I think using `MIOPEN_REQUIRES(!std::is_enum<T>{})`(or `class=std::enable_if_t<!std::is_enum<T>{}>` without the macro) would prevent the issue from occurring again and it doesnt require refactoring a bunch of code. I think it is better for a short-term fix until the check is upstreamed in clang.

**Comment by atamazov** [comment]
@pfultz2 Thanks for detailed explanations and proposals.

Unfortunately, `MIOPEN_REQUIRES` covers only a small subset of potential problems with unscoped enums.

WRT adding clang-tidy check I will either do it myself or ask compiler guys to implement it (as they have everything on hand). However, a lot of time will pass before the appearance of this check in the next release of ROCm. Do you advise to just abandon the API wrapper (line #1608) and wait? Note that the wrapper may be useful to us in the future for some other purposes. For example, we may wish to wrap other unscoped enums etc.

**Comment by pfultz2** [comment]
> WRT adding clang-tidy check I will either do it myself or ask compiler guys to implement it (as they have everything on hand).

Here is the review for llvm: https://reviews.llvm.org/D129570

> Do you advise to just abandon the API wrapper (like https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1608) and wait?

I personally would think it would be better to wait as the wrappers might introduce other issues in the future that may be harder to diagnose, but its up to you.

**Comment by ppanchad-amd** [comment]
@atamazov Is this ticket still relevant? Thanks!

**Comment by atamazov** [comment]
Too much efforts, small effect
