### ISSUE TITLE
What layouts does MIOpen support?

### ISSUE THREAD

**Issue by densamoilov** [ROCm/MIOpen#1620]
From the documentation it's not clear what layouts are supported in MIOpen in general and in operations in particular.
Documentation for [miopenSet4dTensorDescriptor](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/tensor.html#miopenset4dtensordescriptor) has a confusing message that " MIOpen currently only implements NCHW layout". I find it confusing because there is another API - `miopenSetTensorDescriptor` that allows to create a tensor descriptor for the given dimensions and strides meaning that it's possible to create it for NHWC and other layouts.

I  have a few questions:
1. What operations in MIOpen do support NHWC layout? Are those optimized? I found that a new enumeration type for layouts was recently introduced. It looks like it's not the final solution based on a discussion here (https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1532), but the code gives a hint on what layouts are supported by MIOpen: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/8b7e20c0d94a7a0a5acaab260e45aa8047c45672/include/miopen/miopen.h#L349-L360
2. How does `miopenSetTensorDescriptor ` interpret the given dimensions based on the number of dimensions? For example, is it correct to assume that MIOpen has the following interpretation: NC: `dims = [n, c]`, NCW: `dims = [n, c, w]`, NCHW: `dims = [n, c, h, w]`, NCDHW: `dims = [n, c, d, h, w]`?

**Comment by densamoilov** [comment]
@JehandadKhan, @junliume, friendly ping.

**Comment by junliume** [comment]
@JehandadKhan @zjing14 could you help with the question?

**Comment by JehandadKhan** [comment]
@densamoilov 

1. Support in MIOpen for NHWC layout is currently limited to Convolutions and BatchNorm. With convolutions being performance optimized while for BatchNorm the optimized kernels are in development. The `enum` that you refer to is currently only targeting convolutions as you can see from the linked PR. 
2. Your interpretation for the `miopenSetTensorDescriptor` API is correct.

Please let me know if you have additional questions.

**Comment by densamoilov** [comment]
@JehandadKhan, thanks for the clarification. I have one more question regarding 3D spatial formats. What operations do support NCDHW and NDHWC?

**Comment by JehandadKhan** [comment]
@densamoilov  Only convolutions support 3D layouts, and both of the above are supported.

**Comment by ppanchad-amd** [comment]
@densamoilov Please advise if we can go ahead and close this ticket? Thanks!

**Comment by densamoilov** [comment]
@ppanchad-amd, yes, the ticket can be closed, thanks.
