### ISSUE TITLE
Merging Perf DB and Find DB

### ISSUE THREAD

**Issue by JehandadKhan** [ROCm/MIOpen#174]
MIOpen currently has two databases:

* Perf DB with the perf parameters for kernels 
* Find DB with comparative information about the different algorithms

Both these databases share the same key ( derived from the problem description) and therefore it may be useful to merge the two. This would reduce the number of files installed by MIOpen ( only one `miopen .db` ) as compared to one for each arch/cu/backend combination ( In case of Find DB).

This would also simplify the installation in environments where minimal number of files is preferred.

Moreover, due to the structure of `miopen.db` it would simplify tasks such as compiling only the best kernel for a given config, which is complicated right now since they are different files and therefore different databases. 

From an implementation perspective this is simple since different information would be stored in different tables.

My question to the team is, what would be the down side of this ? What are the arguments against this ?

**Comment by pfultz2** [comment]
I think we can merge the system dbs, but the user dbs should be separate files since we will version them differently. Finddb will version based on the miopen version including the tweak(which contains the rocm release), but the perfdb will just sue the schema version.

**Comment by atamazov** [comment]
The down side would be wall time regression of Immediate, Fast Find and Hybrid Find modes.

**Comment by pfultz2** [comment]
> The down side would be wall time regression 

Is there? I have yet to see any perf numbers for this. It seems parsing raw text files would be much slower than using sqlite db.

**Comment by atamazov** [comment]
@pfultz2 We use in-memory caching of system fin-db in `std::map`. I tested it but I didn't published detailed results. I can re-test and publish detailed results.

W.r.t User-find-db in-memory caching: testing was done as well, and average numbers published at https://github.com/AMDComputeLibraries/MLOpen/pull/1968.

**Comment by atamazov** [comment]
@ppanchad-amd Small comment: This should have been closed as "Not planned" 😉
