### ISSUE TITLE
Pruning Solvers from MIOpen

### ISSUE THREAD

**Issue by JehandadKhan** [ROCm/MIOpen#181]
[Link to Excel Sheet](https://amdcloud-my.sharepoint.com/:x:/g/personal/jkhan_amd_com/EbnODXXEQ9BMtZ761J5Y9s4BPh17yPhe3fqD3kBJpv6Y4w?e=dcUzsE)

In an effort to reduce the clutter in our library as well as ensure economy of effort, I ran some analysis on our find db to determine which solvers are usually picked for various configs, as a result of the latest tuning runs. These were run of gfx906 / 60 CU machines. 

This data is primarily aimed at removed solvers that are no longer used, or at least used not often enough. Given our data we can also determine which would be the next wining solver and what would be the impact of such decisions. Please review the attached excel sheet and reach our if you have any questions or have additional queries that need to be answered. I tried my best to be as comprehensive in terms of useful fields that might be of interest to the team.

FYI: @daniellowell @asroy

**Comment by atamazov** [comment]
Thank you for collecting the data, Jehandad. AFAICS it lists the "best" solvers from our find-db (that contains about of 56K configs).

Could you please check BF16 data? The following are not applicable but listed as "the best":

cmd | solver | direction | Count
-- | -- | -- | --
convbfp16 | ConvAsm1x1U | B | 32
convbfp16 | ConvAsm1x1U | F | 180
convbfp16 | ConvAsm1x1UV2 | B | 6
convbfp16 | ConvAsm1x1UV2 | F | 10
convbfp16 | ConvAsm3x3U | F | 6
convbfp16 | ConvAsmBwdWrW3x3 | W | 40

If such records reside in find-db, then affected configs are experiencing:
- Wall time regression in Hybrid Find (fallback to normal Find)
- Perf drop in Fast Find (fallback to Gemm)
- Possibility of performance drop in Immediate mode
- Note: _No correctness problems_.

**Comment by JehandadKhan** [comment]
You are right, that does sound like a bug. Let me investigate

**Comment by JehandadKhan** [comment]
@alexandraBara  Can you please look at these configs? From the database it seems that they were actually run and produced "valid" results. As @atamazov  points out above that should not be the case. There is a bug somewhere.

**Comment by atamazov** [comment]
Right now this is a bug for Alex to triage...

**Comment by JehandadKhan** [comment]
That error was fixed, I have updated the sheet with new numbers.

**Comment by atamazov** [comment]
Good, thanks! By #171?

**Comment by JehandadKhan** [comment]
No, there was an error in Tuna

**Comment by atamazov** [comment]
Aha, so the system fdb we have in develop right now is not affected by this bug, right?

**Comment by asroy** [comment]
@JehandadKhan Which rocm version is this? Is ```MIOPEN_DEBUG_IMPLICIT_GEMM_FIND_ALL_SOLUTIONS``` set to 0 or 1?

**Comment by JehandadKhan** [comment]
@asroy `MIOPEN_DEBUG_IMPLICIT_GEMM_FIND_ALL_SOLUTIONS` would be at its default value.

**Comment by JehandadKhan** [comment]
> Aha, so the system fdb we have in develop right now is not affected by this bug, right?

The system find db should not have this bug.

**Comment by atamazov** [comment]
@asroy @JehandadKhan 
> `MIOPEN_DEBUG_IMPLICIT_GEMM_FIND_ALL_SOLUTIONS` would be at its default value.

It is disabled by default ((

**Comment by atamazov** [comment]
There is https://github.com/AMDComputeLibraries/MLOpen/pull/2520 that woukarounds SWDEV-227826.

**Comment by atamazov** [comment]
@asroy @JehandadKhan 
> `MIOPEN_DEBUG_IMPLICIT_GEMM_FIND_ALL_SOLUTIONS` would be at its default value.

- It is disabled by default :( There is https://github.com/AMDComputeLibraries/MLOpen/pull/2520 that workarounds SWDEV-227826.
- Also it seems like https://github.com/AMDComputeLibraries/MLOpen/issues/2518 is forgotten. I am afraid that the order of iGemm Solvers is still far from optimal. 

These two bullets together mean that the fastest iGemm solvers could be missed :face_with_head_bandage:

**Comment by atamazov** [comment]
@asroy @JehandadKhan 
> `MIOPEN_DEBUG_IMPLICIT_GEMM_FIND_ALL_SOLUTIONS` would be at its default value.

- It is disabled by default :( There is https://github.com/AMDComputeLibraries/MLOpen/pull/2520 that workarounds SWDEV-227826.
- Also it seems like https://github.com/AMDComputeLibraries/MLOpen/issues/2518 is forgotten. I am afraid that the order of iGemm Solvers is still far from optimal. 

These two bullets together mean that the fastest iGemm solvers could be missed :face_with_head_bandage:

**Comment by JehandadKhan** [comment]
That is unfortunate. @asroy are there any other env vars that I should be aware of? I plan on re-running this this week and would be helpful to setup the proper env, please advise.

**Comment by JehandadKhan** [comment]
> * Also it seems like [AMDComputeLibraries/MLOpen#2518](https://github.com/AMDComputeLibraries/MLOpen/issues/2518) is forgotten. I am afraid that the order of iGemm Solvers is still far from optimal.

If we enable the env variable, the order is no longer an issue. At least data collection would  yield actionable results.

**Comment by atamazov** [comment]
@JehandadKhan 
> If we enable the env variable, the order is no longer an issue. At least data collection would yield actionable results.

It's true. The problem is that perf-db (most likely) does not contain information for the solvers to be enabled, so the collected data will still be inaccurate ;(

**Comment by JehandadKhan** [comment]
> It's true. The problem is that perf-db (most likely) does not contain information for the solvers to be enabled, so the collected data will still be inaccurate ;(

We can get around that by using an env var to do a find and disable find-db access

**Comment by atamazov** [comment]
I mean that solvers to be enabled are not tuned yet. Or I do not understand something...?

**Comment by JehandadKhan** [comment]
@atamazov I follow you now, I will see what I can do to fix that.

**Comment by atamazov** [comment]
@JehandadKhan Let me clarify the objective of "pruning solvers" how I see it. I would like to find that Solvers that never win, and remove those from the library. Are we on the same page?

**Comment by ce1adon** [comment]
@JehandadKhan  I notice that the excel table in your comment at top is dated Apr 28. Have there been any changes to the best solver db since then?

**Comment by JehandadKhan** [comment]
@ce1adon Indeed, this table can certainly be updated.

**Comment by JehandadKhan** [comment]
Closing as complete
