### ISSUE TITLE
Use shorter name for iGEMM kernel wrapper

### ISSUE THREAD

**Issue by asroy** [ROCm/MIOpen#183]
@asroy I mean this `gridwise_convolution_backward_data_implicit_gemm` is always the same (except "backward_data" of course), so I would replace it with smth like `gw_conv_fwd/bwd/wrw_igemm` or even `conv_igemm_gw_fwd/bwd/wrw`...

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/145_

**Comment by DrizztDoUrden** [comment]
I think you are meaning something other than #145, which is igemm data invokers PR ;)

**Comment by ppanchad-amd** [comment]
Apologies for the lack of response. Please try latest ROCm 6.0.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.

**Comment by ppanchad-amd** [comment]
@asroy @zjing14 @TejashShah  Is this resolved in latest ROCm 6.1.1? Thanks!

**Comment by taylding-amd** [comment]
Thank you for bringing up the issue! However, after discussing it with the component team, we have decided to keep the current implementation. Please feel free to ask follow-up questions should further assistance be required. Thanks!
