### ISSUE TITLE
build fails when adding add_subdirectory(sqlite)

### ISSUE THREAD

**Issue by jdgh000** [ROCm/MIOpen#2258]
It appears errors is emanating from this line:
add_subdirectory(sqlite) in src/CMakeLists.txt

-- Clang tidy found: 16.0.0git
-- Clang tidy checks: *,-abseil-*,-altera-*,-android-cloexec-fopen,-bugprone-easily-swappable-parameters,-bugprone-exception-escape,-bugprone-macro-par>
-- Found LATEX: /usr/bin/latex
CMake Error at src/CMakeLists.txt:30 (add_subdirectory):
  add_subdirectory given source "sqlite" which is not an existing directory.

-- MIOpen_VERSION= 2.19.0
-- CMAKE_BUILD_TYPE= Release

Also see following errors continuing:

CMake Error: File /root/../MIOpen/src/kernels/kernel.cpp.in does not exist.
CMake Error at src/CMakeLists.txt:80 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  src/CMakeLists.txt:469 (add_kernels)

**Comment by dmikushin** [comment]
Hi @jdgh000 , the sqlite subdirectory [exists](https://github.com/ROCmSoftwarePlatform/MIOpen/tree/develop/src/sqlite). Maybe it does not exist for you due to the dirty repository state? Please check with `git diff` or `git checkout src/sqlite`.

**Comment by jdgh000** [comment]
i am not understanding your response. 
It is not documented anywhere in your build instruction.  Secondly, how could frehsly checkout repository could be dirty?
Are you even aware of what you are saying?

Here is the environment info: 
/root/ROCm5.5/MIOpen# git checkout src/sqlite  
error: pathspec 'src/sqlite' did not match any file(s) known to git.

git branch -r
m/roc-5.5.x -> rocm-5.5.1

**Comment by junliume** [comment]
Hi @jdgh000 could you please provide steps to reproduce your issue?

> /root/ROCm5.5/MIOpen# git checkout src/sqlite
> error: pathspec 'src/sqlite' did not match any file(s) known to git.

This error does look like as if you do not have `${MIOpen}/src/sqlite` directory, which should exist when you pull or download MIOpen, as shown here: https://github.com/ROCmSoftwarePlatform/MIOpen/tree/release/rocm-rel-5.5/src/sqlite

May I ask if you could check the integrity of your local repo? Maybe something gets deleted accidentally but we cannot be sure without a clear procedure to reproduce this issue.

Thanks!

**Comment by jdgh000** [comment]
but i posted above already, that 5.5 does not have it. Did you see the post, here are full steps

Used to checkout using manifest.xml all components incl. MIOpen:

https://github.com/RadeonOpenCompute/ROCm/blob/docs/5.5.0/default.xml.
    echo "repo init..."
    ~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-5.5.x
    ~/bin/repo sync

cd ROCm5.5/MIOpen
    git lfs install
    git add .gitattributes
    mkdir build; cd build
    CXX=/opt/rocm/llvm/bin/clang++ cmake $CONFIG_MIOPEN_BUILD_ROCBLAS -DMIOPEN_BACKEND=HIP -DMIOPEN_HIP_COMPILER=/opt/rocm/llvm/bin/clang++ 
make

**Comment by junliume** [comment]
@jdgh000 thanks for providing the steps. However, I followed it and cannot reproduce the issue (details below).
May I ask if you have cleaned or wiped MIOpen directory after the first and unsuccessful attempt of `repo sync` ?

- Step 1: install `repo`
  ```
  # mkdir ~/bin
  # PATH=~/bin:$PATH
  # curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 45787  100 45787    0     0   502k      0 --:--:-- --:--:-- --:--:--  502k
  # chmod a+x ~/bin/repo
  ```

- Step 2: sync the repos
after the normal `git` settings:
  ```
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
  ```
  then
  ```
  # ~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-5.5.x
  # ~/bin/repo sync

  git-lfs filter-process --skip: 1: git-lfs: not found
  fatal: the remote end hung up unexpectedly
  error.GitError: Cannot checkout MIOpen: Cannot initialize work tree for MIOpen
  error: Cannot checkout MIOpen
  Updating files: 100% (2008/2008), done.
  Updating files: 100% (78663/78663), done.ng files:  31% (24386/78663)
  Updating files: 100% (37681/37681), done.
  Updating files: 100% (122033/122033), done.
  Checking out: 100% (54/54), done in 19.585s
  
  
  error: Unable to fully sync the tree
  error: Checking out local projects failed.
  Failing repos:
  MIOpen

  ```

- Step 3:  correct the error (not having `git lfs` and then check if the directory exists or not:
```
  # sudo apt-get install git-lfs
  # rm -rf MIOpen && ~/bin/repo sync

  repo sync has finished successfully.

  # ls MIOpen/src/sqlite
  CMakeLists.txt  memvfs.cpp

```

**Comment by jdgh000** [comment]
can you check output of 
git branch -r from miopen repo? 
I dont see sqlite directory with following checkout:

~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-5.5.x
~/bin/repo sync

**Comment by junliume** [comment]
@jdgh000 here are the output from my end:
```
node:/var/lib/jenkins# ~/bin/repo init -u https://github.com/RadeonOpenCompute/ROCm.git -b roc-5.5.x

... A new version of repo (2.35) is available.
... You should upgrade soon:
    cp /var/lib/jenkins/.repo/repo/repo /root/bin/repo

repo: reusing existing repo client checkout in /var/lib/jenkins

repo has been initialized in /var/lib/jenkins

node:/var/lib/jenkins# ~/bin/repo sync

... A new version of repo (2.35) is available.
... You should upgrade soon:
    cp /var/lib/jenkins/.repo/repo/repo /root/bin/repo

Fetching: 100% (55/55), done in 0.343s
Checking out: 100% (54/54), done in 3.444s
repo sync has finished successfully.

node:/var/lib/jenkins# cd MIOpen
node:/var/lib/jenkins/MIOpen# git branch -r
  m/roc-5.5.x -> rocm-5.5.1
node:/var/lib/jenkins/MIOpen# ls src/sqlite
CMakeLists.txt  memvfs.cpp
```

**Comment by jdgh000** [comment]
when i checkout afresh, i do see sqlite directory. it is unclear how the directory not to be there on previous check, i will do some digging on this. I havent deleted any files only made an attempt to build miopen.

**Comment by jdgh000** [comment]
i am building it now it appears to be going further. the sqlite directory appears to be due to git-lfs missing. It is unique in the state that most prerequisite packages such this are required before the building but git-lfs is **prerequisite before even checking out** the source code. You may wanna state in your documentation clearly.

**Comment by junliume** [comment]
@cderb could you help on updating MIOpen build instructions? Thanks!

**Comment by dmikushin** [comment]
@jdgh000 It remains quite unclear to me how sqlite directory relates to git-lfs. In a nutshell, LFS is a plugin, which optionally overlays some big files on top of a regular git repo. That is, a git repo should always be in a completely healthy state, even if git-lfs is not installed. Without LFS, the files that are supposed to be provided by LFS would appear as zero-size files. AFAIK, this is the maximum "damage" that a missing LFS could do to a git repository. The files managed by LFS are described by `.gitattributes` file. This file clearly appoints only .kdb files a subject to LFS, which again leaves me clueless about your point.

**Comment by jdgh000** [comment]
it is unclear to me as well. i will see if i can sort out. 
i started seeing error with kdb and then took care of it by installing then sqlite became error.

**Comment by jdgh000** [comment]
with git-lfs installed, i see build is ok with 5.5. I see build still fails with following error on 5.6:

```
In file included from /root/gg/git/codelab-scripts/build-install-scripts/rocm/ROCm-5.6/MIOpen/src/include/miopen/op_kernel_args.hpp:6:
/opt/rocm/include/half.hpp:22:2: warning: "This file is deprecated. Use the header file from /opt/rocm-5.6.0/include/half/half.hpp by using #include <h>
#warning "This file is deprecated. Use the header file from /opt/rocm-5.6.0/include/half/half.hpp by using #include <half/half.hpp>"
 ^
/root/gg/git/codelab-scripts/build-install-scripts/rocm/ROCm-5.6/MIOpen/src/hip/handlehip.cpp:343:42: error: no member named 'add_resours' in 'miopen::>
            this->impl->ms_resourse_ptr->add_resours(std::move(new_stream));
            ~  ^
1 warning and 1 error generated when compiling for gfx1030.
make[2]: *** [src/CMakeFiles/MIOpen.dir/build.make:28742: src/CMakeFiles/MIOpen.dir/hip/handlehip.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1421: src/CMakeFiles/MIOpen.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

```

**Comment by jdgh000** [comment]
> @jdgh000 It remains quite unclear to me how sqlite directory relates to git-lfs. In a nutshell, LFS is a plugin, which optionally overlays some big files on top of a regular git repo. That is, a git repo should always be in a completely healthy state, even if git-lfs is not installed. Without LFS, the files that are supposed to be provided by LFS would appear as zero-size files. AFAIK, this is the maximum "damage" that a missing LFS could do to a git repository. The files managed by LFS are described by `.gitattributes` file. This file clearly appoints only .kdb files a subject to LFS, which again leaves me clueless about your point.

This appears murky as ever. I see sometimes error during repo sync. But I also see sometimes clone is possible without git-lfs. It seems intermittent. I just ensured that git-lfs is isntalled before doing anything,

**Comment by dmikushin** [comment]
AFAIK, clone should definitely be possible without git-lfs. I think the variety of issues you are experiencing indicates filesystem or storage hardware problem. If you have some spare RAM, please try to git clone to /dev/shm and make sure no issues are there.
