### ISSUE TITLE
Potentially wrong offset calculation in the use of buffer intrinsic

### ISSUE THREAD

**Issue by asroy** [ROCm/MIOpen#469]
For this JIRA filed originally as compiler bug for ROCm-3.7/3.8 (also failed on 3.5)
http://ontrack-internal.amd.com/browse/SWDEV-251757
http://ontrack-internal.amd.com/browse/SWDEV-247082

However, the failure may potentially due to mis-use of buffer intrinsic:

@ekuznetsov139 think this may be due to a combination of following things:
1) Fp32 pass use the deprecated buffer intrinsic, where user provide a single offset "all_offset" and compiler break it down to Soffset, Voffset, Immed_offset: all_offset = Soffset + Voffset
2) llvm intrisnc takes int32_t as offset, the kernel also use in32_t for offset, and may have negative values (Soffset, Voffset immed_offset have be negative). However, for buffer instructions, Soffset and Voffset need to be uint32_t. This maybe some negative value interpreted as unsigned value and result in wrong addr.

Several observation that support the hypothesis (negative offset)
1) when using -O1, compiler will not break all_offset into Soffset, Voffset, immed_offset, and instead put "all_offset" entirely into Voffset. The result will be correct
2) when disabling buffer intrinsic completely, the result will be correct.  

Failed config using buffer intrinsic and -O3 compilation flag:
```
 bin/MIOpenDriver conv -F 2 -n 32 -c 128 -H 38 -W 38 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 32 -c 256 -H 38 -W 38 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 32 -c 256 -H 38 -W 38 -k 512 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 32 -c 512 -H 19 -W 19 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 32 -c 256 -H 19 -W 19 -k 512 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 64 -H 256 -W 256 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 256 -H 256 -W 256 -k 64 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 256 -H 256 -W 256 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 512 -H 128 -W 128 -k 128 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 512 -H 128 -W 128 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 1024 -H 64 -W 64 -k 256 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 4 -c 512 -H 128 -W 128 -k 12 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 800 -c 256 -H 7 -W 7 -k 1024 -y 7 -x 7 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 800 -c 1024 -H 1 -W 1 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -t 1
 bin/MIOpenDriver conv -F 2 -n 800 -c 256 -H 28 -W 28 -k 256 -y 2 -x 2 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -t 1
```

Need to come up with a solution to fix it

**Comment by daniellowell** [comment]
@asroy This one is 3 weeks old. What update do you have here?

**Comment by asroy** [comment]
The ticket is only a speculation of root cause the failure in http://ontrack-internal.amd.com/browse/SWDEV-251757

This ticket is not blocking anything AFAIK

There is no update from compiler team in the JIRA. I will just leave this issue open until compiler team get down to the bottom of it and either confirm or disagree with our speculation.

**Comment by atamazov** [comment]
Let's assume this is not a MIOpen bug for now (see previous comment)
