### ISSUE TITLE
Need double check vector read length for ConvHipImplicitGemmForwardV4R4Xdlops_Padded_Gemm

### ISSUE THREAD

**Issue by asroy** [ROCm/MIOpen#476]
Still not sure we have got it correct, need to double check some other time.

=====================================
should be:
```SrcDataPerRead_GemmKPack = gcd(SrcDataPerRead_GemmKPack, gemm_k_real % GemmKPack);```

because you want to make sure ```SrcDataPerRead_GemmKPack```is a factor or ```gemm_k_real % GemmKPack``` not ```gemm_k_extra```

(I don't know what you call ```gemm_k_real``` in your code though, haven't read all the code)

_Originally posted by @asroy in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/444#discussion_r497249064_

=====================================

B do not need this due to gcd with ho before

_Originally posted by @asleepzzz in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/444#discussion_r497291459_

**Comment by ppanchad-amd** [comment]
Please try latest ROCm 6.0.2 to see if your issue still occurs? If is not reproducible, please close the ticket. Thanks.

**Comment by ppanchad-amd** [comment]
@asroy Is this ticket still relevant? If not please close. Thanks!
