### ISSUE TITLE
WORKAROUND_SWDEV_227826 should not affect iGEMM solvers written in ASM

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#483]
Originated from https://github.com/AMDComputeLibraries/MLOpen/issues/2535#issuecomment-702984109.

I expect that importance of this will grow over time.

/cc @daniellowell @asroy @JehandadKhan

**Comment by asroy** [comment]
PR #488 would remove this workaround, so all iGEMM solver will be enabled by default.

**Comment by ppanchad-amd** [comment]
@atamazov Is this still a relevant issue?

**Comment by atamazov** [comment]
WORKAROUND_SWDEV_227826 is disabled in #1595.
