### ISSUE TITLE
Support for different tensor layouts

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#509]
This is follow-up of #343, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/343#discussion_r495241947 and other comments there.

The goal is to get uniform support for different tensor layouts at the architecture level, in all library components. Presumably, at first, we need to add layout information into problem description (which solvers or algorithms will support them is another matter).

**Comment by atamazov** [comment]
> we need to add layout information into problem description

The problem is already solved in the `miopen::conv::ProblemDescription` class. It aggregates the copies of tensor descriptors, that contain strides and provide the `GetLayout()` method (that implements approach as proposed at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/343#discussion_r471737474).

**Comment by ppanchad-amd** [comment]
@atamazov Is this ticket still relevant? Does it need to be kept open? Thanks!
