### ISSUE TITLE
Reference (naive) kernel tasks

### ISSUE THREAD

**Issue by carlushuang** [ROCm/MIOpen#593]
This issue is to track reference kernel features in MIOpen

- [x] 1. MIOpenDriver verification backend (PR:https://github.com/ROCmSoftwarePlatform/MIOpen/pull/583, by setting env var `MIOPEN_DRIVER_USE_GPU_REFERENCE`)
- [x] 2. Direct algorithm solver. (PR:https://github.com/ROCmSoftwarePlatform/MIOpen/pull/583, can solve issue: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/588)
- [ ] 3. ctest verification backend (not implemented yes)
- [ ] 4. NHWC

cc @daniellowell @atamazov @asroy @zjing14

**Comment by atamazov** [comment]
[Question] Shall we integrate it into Immediate Mode Fallback?

**Comment by carlushuang** [comment]
Hi @atamazov I believe ultimately we need implicit-gemm as a fallback. But before that happen, these naive kernel is OK to play the role.

**Comment by JehandadKhan** [comment]
@carlushuang i assume this would be a dynamic kernel ?

**Comment by carlushuang** [comment]
@JehandadKhan yes, it is dynamic

**Comment by ppanchad-amd** [comment]
Closing bug.

Item 1,2 and 4 implemented 3 years ago. Item 3 rejected.
