### ISSUE TITLE
[gfx10] CU count reported by HIP & OCL runtime have different meaning

### ISSUE THREAD

**Issue by Kirpich30000** [ROCm/MIOpen#654]
Looks like runtime will report number of WGPs instead of CUs. In that case winograd shader will be dispatched only on half of the gpu. It needs to be checked.

**Comment by atamazov** [comment]
Which runtime, OCL or HIP?

**Comment by Kirpich30000** [comment]
Both

**Comment by atamazov** [comment]
Not a bug in runtimes, I guess?

**Comment by ppanchad-amd** [comment]
@Kirpich30000 Please check if this still an issue with ROCm 6.0.2? If this is no longer an issue, please close the ticket. Thanks!

**Comment by Kirpich30000** [comment]
Should be closed as implemented
