### ISSUE TITLE
Double check a tuning parameter from perfdb

### ISSUE THREAD

**Issue by zjing14** [ROCm/MIOpen#668]
Issue
------
- Current MIOpen does not check the validation of a tuning parameter from perfdb. Thus, after fixing the tuning of a solver, we need to re-tune perfdb, otherwise, problematic tuning parameters will still be loaded.

Solution
------
- Double-check the validation of a tuning parameter loaded from perfdb; if it is invalid, get a default tuning parameter
- Better to have the infrastructure in place for all solvers
- Minimize the overhead of validation

**Comment by daniellowell** [comment]
This is an issue that can occur in the field if we fail to detect an error during testing. Or also in our CI if a perf-db exists that contains un-updated config for a solver.

**Comment by junliume** [comment]
@JehandadKhan it looks like a perf_db issue which might have been resolved already? Can we close this issue?

**Comment by atamazov** [comment]
> Current MIOpen does not check the validation of a tuning parameter from perfdb. Thus, after fixing the tuning of a solver, we need to re-tune perfdb, otherwise, problematic tuning parameters will still be loaded.

This is incorrect statement. The core of the library implements full support for this.

However each solver must provide correct implementation of `bool IsValidPerformanceConfig(ProblemDescription&, PerformanceConfig&)` (please see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/866#issuecomment-822585406 for more info). If this is not done, then the performanceConfig validation problems may occur.

I am proposing either closing this ticket or clarifying which solvers have this problem (+use cases). Thanks.

**Comment by atamazov** [comment]
@ce1adon 
> Double-check the validation of a tuning parameter loaded from perfdb; if it is invalid, get a default tuning parameter

:+1: Luckily, we already have this.
