### ISSUE TITLE
[RNN][OCL BE] test_lstm fails due to OCL compiler warning

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#692]
- The test fails with compiler mainline builds 6326 and 6416 at least.
- Most likely, the reason is change in the compiler - a new warning was added recently or some bug (false warning) introduced.
- Who is affected
  - The problem should NOT affect the end users (warnings do not lead to errors in non-developer builds)
  - QA should not be affected because they use non-developer builds as well.
  - All developers who work with compiler mainline.
  - Our CI, but not now -- after we upgrade CI to ROCm 4.1.
- What looks suspicious to me is that compiler clams that `n_work_groups_with_1_more == 0` which is indeed strange and my be a symptom of incorrectness in miopengemm (affects only OCL backend).

Due to all the above, let's assign the high priority.

Error log:
```
root@morpheus:/atamazov-github/MLOpen1/build/6416.release.opencl# ./bin/test_lstm
Empty batch sequence. Filling uniformly with batch size: 17
MIOpen(OpenCL): Info [Handle] Device name: gfx906:sramecc-:xnack-
MIOpen(OpenCL): Info [Handle] stream: 0x55aadb1d85e0, device_id: 0x55aadb1ab970
MIOpen(OpenCL): Error [BuildProgram] Build log: /tmp/comgr-e9c850/input/CompileSource:182:62: error: result of comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-unsigned-zero-compare]
  int n_unrolls_remaining = (KV__ / G_UNROLL) +  (group_id_z < n_work_groups_with_1_more);
                                                  ~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error: Failed to compile opencl source (from CL or HIP source to LLVM IR).
```

How to reproduce (Radeon VII):
- Pull code from PR #690 
- Pull docker w/mainline build 6326 or 6416
- Add `-DMIOPEN_OVERRIDE_HIP_VERSION_MINOR=1` to cmake command line when building MIOpen
- Build for OpenCL backend
- Run `test_lstm`

/cc @daniellowell

**Comment by ce1adon** [comment]
@atamazov Which architecture?

**Comment by atamazov** [comment]
> How to reproduce (Radeon VII):...

This is gfx906.

**Comment by ce1adon** [comment]
It's not replicable locally with 6416.

**Comment by ce1adon** [comment]
The issue is in miopengemm. Let's temporarily disable this test in ocl backend to remove the blocker first.

**Comment by atamazov** [comment]
Please go ahead.

**Comment by ce1adon** [comment]
Please track http://ontrack-internal.amd.com/browse/SWDEV-270602

**Comment by atamazov** [comment]
Description updated. Priority lowered to high.

**Comment by atamazov** [comment]
Workaround merged. Fix in MIOpenGEMM is on the way.

**Comment by ppanchad-amd** [comment]
@atamazov Seems like there is a fix for this in MIOpenGEMM? Please confirm and close ticket.  Thanks!

**Comment by atamazov** [comment]
OCL BE is deprecated.

**Comment by atamazov** [comment]
OCL BE is deprecated.
