### ISSUE TITLE
[OpenCL backend] Remove HIP unbundling when OCL runtime is ready

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#697]
Remove HIP unbundling from OpenCL BE as soon as [loading bundled program is added to OpenCL runtime](http://ontrack-internal.amd.com/browse/SWDEV-268562).

_Originated from https://github.com/ROCmSoftwarePlatform/MIOpen/pull/685#issue-556245151_

**Comment by ppanchad-amd** [comment]
@atamazov Is this ticket still relevant?

**Comment by atamazov** [comment]
OCL BE is deprecated
