### ISSUE TITLE
Throw-catch-based logics

### ISSUE THREAD

**Issue by DrizztDoUrden** [ROCm/MIOpen#712]
Some implicit gemm solvers are using throw and catch for logic, which gets called often. It is a bad approach in general and clutters I-level log a lot. Would be nice to change that to explicit return instead of a throw.
An example (a catch is a couple of lines below, more throws above): https://github.com/ROCmSoftwarePlatform/MIOpen/blob/98fb10e69bbe463f34f36ea9af9da6a372a2d02a/src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp#L251

**Comment by atamazov** [comment]
This pattern should not be used. Code redesign is required. Please ask for assistance/ideas, if necessary.

**Comment by atamazov** [comment]
This is leftover from https://github.com/AMDComputeLibraries/MLOpen/pull/2407#discussion_r380260415, collected at https://github.com/AMDComputeLibraries/MLOpen/issues/2421 but not fixed anyway.

**Comment by ppanchad-amd** [comment]
@DrizztDoUrden Please check if this issue is reproducible with latest ROCm 6.0.2? If not reproducible, please close ticket. Thanks!
