### ISSUE TITLE
Expect to support buffer offset argument for MIOpen DNN Forward/Backward APIs

### ISSUE THREAD

**Issue by ghostplant** [ROCm/MIOpen#75]
Hi, the current internal implementation of MIOpen DNN algorithm should allow to set buffer offset argument, but the external APIs just hide them so there is no way for users to set these values externally.

External API:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/activ_api.cpp#L87

Internal API:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/ocl/activ_ocl.cpp#L41

Do you have existing suggestions or enhancement plans? I really need this to be supported and I'll also be happy to provide some development support.

**Comment by ghostplant** [comment]
Because OpenCL memory buffer is very not flexible to share and manage, so it doesn't support memory offset computation at host program which is bad.

Thus, I requires something like:
```sh
# By extending offset arguments to external miopen APIs:
miopenActivationForward(miopenHandle_t handle, .., size_t xOffset = 0, , size_t yOffset = 0)
```
or
```sh
# By extending another API that contains offset arguments:
miopenActivationForward(miopenHandle_t handle, ..)
miopenActivationForwardWithOffset(miopenHandle_t handle, .., size_t xOffset, , size_t yOffset)
```
or the most preferred one
```
# By preconfiguration handle to use a base memory buffer
miopenSetMemBufferBase(cl_mem base_buffer);
# treat x, y to be the value of offset
miopenActivationForward(miopenHandle_t handle, void *x, void *y)
```

**Comment by daniellowell** [comment]
In your case you are not able to specify sub-buffer creation in OpenCL?

**Comment by ghostplant** [comment]
`sub-buffer` requires offset alignment which is hardly suitable in most cases.

**Comment by ppanchad-amd** [comment]
Apologies for the lack of response. Please try latest ROCm 6.0.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.

**Comment by atamazov** [comment]
@ghostplant Please notice that OpenCL backend is deprecated in MIOpen. And in any case, backend-specific entities (cl_mem) can't be exposed in the public API.

However I guess that `miopenActivationForwardWithOffset()` can be implemented. Please let us know if you still need this feature, and please also indicate its importance.

/cc @junliume

**Comment by ppanchad-amd** [comment]
@ghostplant Closing ticket. Please re-open if you still need this feature. Thank!
