### ISSUE TITLE
cudnnRNNBackwardDataEx, padded lstm training api.

### ISSUE THREAD

**Issue by Joejiong** [ROCm/MIOpen#751]
hi, will you guys support cudnnRNNBackwardDataEx equivalent api with miopen? (padded lstm training api)

**Comment by shurale-nkn** [comment]
Hi @Joejiong, cudnnRNNBackwardDataEx was deprecated log time ago in cuda. We have miopenRNNBackwardSeqData, which should be used instead of cudnnRNNBackwardData_v8.
