### ISSUE TITLE
Support for arbitrary strides

### ISSUE THREAD

**Issue by dtarakanov1** [ROCm/MIOpen#80]
MIOpen supports data with the NCHW layout. A tensor descriptor works dimensions in the NCHW order.

A tensor descriptor also requires an array of strides (see e.g. [`miopenSetTensorDescriptor()`](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/tensor.html#miopensettensordescriptor)).

However according to the [kernel code](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3afe80a5c5a72a69ee8d0d8f965cff782d3cde22/src/kernels/MIOpenConvD3x3.cl#L339) there is no such parameter as a height stride, it is always assumed to be equal to 1. This means that if input data is in the NHWC format, they must be physically re-ordered. It's not possible to simply change the strides order to get MIOpen algorithms working.

**Comment by daniellowell** [comment]
@dtarakanov1  Thanks for your comment. Consistent striding is something we need to add across the library. Look for better support in the future releases.

**Comment by ppanchad-amd** [comment]
Apologies for the lack of response. Please try latest ROCm 6.0.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.
