### ISSUE TITLE
Tunable Dynamic Solvers need perf-db interpolation.

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#807]
By definition, if a dynamic Solver is applicable to a _set of configs_, then the same kernel(s) can be used for any config from that _set_ and no performance drop should happen. Therefore, if a Dynamic Solver have been tuned for _one_ config from the set, the resulting optimal performance parameters (PerformanceConfig) should be also optimal for _any other_ config from that set.

[Note 1] If this is not so, then the Solver is not truly Dynamic.

[Note 2] Example of Tunable Dynamic Solver: #680.

However, currently MIOpen is unable to use this feature. All Solvers need tuning for each config. As a consequence:
- (A) The performance of Dynamic Solvers suffers on unseen configs.
- (B) The tuning time could be improved for Dynamic Solvers. Two cases:
  - (B.1) Tuning of known configs conducted by Tuna.
  - (B.2) During autonomous tuning.

[Note 3] For initial description of what is Dynamic kernel, see #398

**Comment by atamazov** [comment]
## Variant 1.

- (A) We can implement the perf-db interpolation feature, see discussion & proposal at: https://github.com/AMDComputeLibraries/MLOpen/issues/1271.
  - Drawback: :red_circle: Perf-db interpolation time is added to the kernel execution time, thus directly affecting the performance.
  - What can we do: :green_circle: Write interpolated PerformanceConfig to the user-perf-db, so that next time interpolation won't happen.

- (B.1) We can ask the Tuna team to handle Dynamic Solvers in some special way.

- (B.2) `MIOPEN_FIND_ENFORCE=SEARCH_DB_UPDATE (4)` should not be used. The user should run two passes instead. The 1st should be `DB_CLEAN (5)` -- it clears the user-perf-db. The 2nd pass should be `SEARCH (3)` -- MIOpen will tune kernels. [[Documentation](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/perfdatabase.md#miopen_find_enforce)]
  - Why this should help: If a Solver has PerformanceConfig for some configuration, then `SEARCH (3)` does NOT re-rune it . So if we have (A) done, then tuning won't happen more than once for a set of applicable configs.
  - Drawback: If we have a suitable record in the System-perf-db, then it will not be re-tuned. If the user wants to re-rune such configs, they will have to return to `SEARCH_DB_UPDATE (4)` and spend more time.

**Comment by ppanchad-amd** [comment]
@atamazov Is this fixed on ROCm 6.0.2? Thanks!

**Comment by atamazov** [comment]
> Therefore, if a Dynamic Solver have been tuned for _one_ config from the set, the resulting optimal performance parameters (PerformanceConfig) should be also optimal for _any other_ config from that set.

This statement is incorrect.
