### ISSUE TITLE
[PR Testing][iGemm] GEMM testing – make the test case tunable to test more GEMM sizes; e.g., 64x64 and 128x128 tests

### ISSUE THREAD

**Issue by aserio** [ROCm/MIOpen#824]
Part of iGEMM Component Testing #586

**Comment by aserio** [comment]
@jane-zxy will you still be working on this ticket?

**Comment by JehandadKhan** [comment]
Static CK in MIOpen is deprecated, these issues in MIOpen are no longer relevant.
