### ISSUE TITLE
Support for broadcast operations

### ISSUE THREAD

**Issue by dtarakanov1** [ROCm/MIOpen#85]
So far there is no straight ways to implement a broadcast operation like `tensor + scalar` or `scalar - tensor`.

A client may e.g. create a new tensor and fill it with the scalar value and then use the `miopenSetTensor()`. However this is a waste of precious GPU memory.

**Comment by daniellowell** [comment]
This looks straight forward to implement. What model is this used?

**Comment by dtarakanov1** [comment]
We are implementing the engine which runs TensorFlow models via MIOpen API.

Basically almost every TF operation supports broadcasting. E.g. `Add`, `Sub`, `Mul`, `Min`, `Max` etc.

I particularly encountered `Sub`, `Min` and `Max` in the preprocessing and postprocessing parts of the graph (data normalization, tone mapping).

**Comment by ppanchad-amd** [comment]
Apologies for the lack of response. Please try latest ROCm 6.0.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.
