### ISSUE TITLE
Check perf-db performance

### ISSUE THREAD

**Issue by atamazov** [ROCm/MIOpen#901]
> The reason of such a high performance gain is time spent for perf-db reads in the baseline. The fastest solver in baseline is ConvHipImplicitGemmBwdDataV4R1Xdlops. It needs performance-config, and reading it from the system-perf-db takes ~190ms. In asm-bwd-fp16, the fastest solver is ConvAsmImplicitGemmGTCDynamicBwdXdlops in many cases; it does not need performance-config. As a result, Aux Wall time for the former case is around 200 ms, but for the latter case it is milliseconds (see attached logs).

@atamazov I believe this is due to the measurement being done with the driver, since each invocation of the driver re-initializes the database, however, in a network once the library is loaded in memory the db is initialized and this is not an issue.

_Originally posted by @JehandadKhan in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/710#issuecomment-828753371_

**Comment by atamazov** [comment]
The driver is run in three directions (Backward is the second one), and there is warm-up pass activated in the driver (`-w 2`). Needs to double check logs (with timestamps) attached to #710.

**Comment by ppanchad-amd** [comment]
@atamazov Is this ticket still relevant?

**Comment by atamazov** [comment]
Now we have perf-db caching, so perf-db performance can't be an issue anymore.
