### ISSUE TITLE
[FR] Expect to support PoolingBWD with zero workspace

### ISSUE THREAD

**Issue by ghostplant** [ROCm/MIOpen#91]
MIOpenPoolingBackwards requires additional workspace while CUDNN doesn't, and this complicates the porting work from CUDNN to MIOpen since it is not easy sometimes to pair the Forwards and Backwards invocations among quantities of pooling operations.

**Comment by lsder** [comment]
Is this FR solved?

**Comment by atamazov** [comment]
@lsder I do not think so. IIRC existing pooling implementations in MIOpen require workspace.

/cc @JehandadKhan @dmikushin

**Comment by ppanchad-amd** [comment]
@ghostplant Apologies for the lack of response. Please try latest ROCm 6.1.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.
