### ISSUE TITLE
[MI100][ROCm 3.7] Re-enable Forward and WrW V4R4Xdlops_Padded_Gem Solvers for BF16 with ROCm 3.7

### ISSUE THREAD

**Issue by asroy** [ROCm/MIOpen#928]
- [ ] Narrow the impact of the workaround in PR #929 to problematic configs, and re-enable Fwd/WrW V4R4 padded_gemm solvers for Bfloat16 with ROCm 3.7.
- [ ] Open compiler JIRA ticket

Some failing configs and example failing log: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/920#issue-640915724

**Comment by atamazov** [comment]
`rocm-4.2.x-staging` contains the same workaround (via PR #920), but does NOT require a full-blown fix.

**Comment by asleepzzz** [comment]
I will look into why bf16 failed

**Comment by ppanchad-amd** [comment]
@asroy Please check if this still an issue on ROCm 6.0.2? If not, please close ticket. Thanks!

**Comment by atamazov** [comment]
@ppanchad-amd WORKAROUND_MI100_BF16_FATAL_COMPILER_ERRORS removed in #2665, issue can be closed as "won't fix"
